### ISSUE TITLE
Problem beim Download

### ISSUE THREAD

**Issue by kr1stov** [VoIarion/TWD#1]
Moin, 

Download, pull und clone brechen auch meinem Rechner immer ab. Kannst du mir da vielleicht als gezipte Datei irgenwo zum Download bereit stellen? Danke.

**Comment by VoIarion** [comment]
Die nicht beleuchteten Bäume in der Ferne sind wohl doch Billboards.
Hast du spontan eine Idee, wie man die mit verdunkeln kann?
Ich bin ansonsten am Freitag wieder an der Uni; könnte das aber auch über Dropbox freigeben.

**Comment by kr1stov** [comment]
Ich versuch das mal mit einer eigenen Szene nachzustellen. Vielleicht find ich ja so ne Lösung.

**Comment by kr1stov** [comment]
Pullen scheint endlich mal geklappt zu haben. In meinen Projekten konnte ich den Bug bisher nicht reproduzieren. Ich schau mir mal dein Projekt an.

**Comment by kr1stov** [comment]
Quick & dirty fix wäre übrigens Fog anmachen in den Light Settings und die Billboards im Nebel verschwinden lassen.

**Comment by kr1stov** [comment]
Vielleicht solltet ihr auch bessere Texturen verwenden. Wie gesagt, bei meinen Tests mit den Texturen aus dem Environment pack tritt der Effekt nicht auf.

**Comment by VoIarion** [comment]
Der fog war für uns schon der backup-plan, aber das bringt entfernte Lichter leider auch zum Verschwinden.
Mal sehn, ob sich das mit nem anderen texture-pack ändert.
